### ISSUE TITLE
ancombc2 row.names error

### ISSUE THREAD

**Issue by jkcopela** [FrederickHuangLin/ANCOMBC#105] opened 2022-10-18 00:39 UTC
Hello,

I am trying to run ancombc2 and I am running into this error when the tax_level is kept as NULL, or specified as Genus, or any tax level with repeated tax names as "uncultured". 

The command I am running: 

out = ancombc2(ps_obj, tax_level = NULL , fix_formula = "SampleType", p_adj_method = "holm", verbose = TRUE, prv_cut = 0.05, global = TRUE, pairwise = TRUE, group = "SampleType")

Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘Genus:uncultured’ 

This message does not occur when I run the exact same phyloseq object through the equivalent ancombc formula.

I am not sure if this is an issue with the data and how it is formatted for taxonomy name (input is an ASV table created in qiime2, as a biom object), or something else?

Thanks for your help!
Julia

**Comment by FrederickHuangLin** [comment] 2022-10-18 01:18
Hi Julia,

Neither `ancombc` or `ancombc2` supports importing raw biom data. You should transfer the biom data to a `TreeSummarizedExperiment` object. For details, you can see this [tutorial](https://microbiome.github.io/OMA/containers.html#import-from-external-files).

Best,
Huang

**Comment by jkcopela** [comment] 2022-10-18 13:30
Hi Huang,

Thanks for your reply! Sorry I was not clear, I meant to say the initial input was a biom file, but converted into a phyloseq object and merged with a tree and metadata file. This is then converted into a TreeSummarizedExperiment object.

This is the input file into the ancombc2 function:

class: TreeSummarizedExperiment 
dim: 360 30 
metadata(0):
assays(1): counts
rownames(360): 7d17d197d7978be0b6684209ce257e20 d624f3cc54840847422f1cf7b6ad4a1d ...
  9154fa6a1f8d4e5c562994121242f5b5 dffa04ca171f459056b9466d7acfe601
rowData names(7): Kingdom Phylum ... Genus Species
colnames(30): 15052 10010019-2 ... A1 A16
colData names(6): SampleID SampleType ... SampleGroup Controls
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
rowLinks: a LinkDataFrame (360 rows)
rowTree: 1 phylo tree(s) (360 leaves)
colLinks: NULL
colTree: NULL

This file produces the error I mentioned above, when the taxa level is not specified (NULL) or a taxa level is specified ("Genus") when there are repeated ASVs labeled as "uncultured" at the genus level. This error does not occur if the taxa level is specified as "Phylum", because there are no repeated Phyla labels. 

This error does not occur with ancombc as I mentioned, so I was just wondering if there is a difference in how the taxa labels are being read?

Thanks,
Julia

**Comment by JeremyTournayre** [comment] 2022-10-18 13:40
Hello,

I have exactly the same question :). 

I'm currently trying to test the pairwise option of ANCOMBC 2 (ancombc2 function) and I have this error message: 

Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘Family:uncultured’ 

I have this problem with the "ancombc" function too.

I don't have this problem with the previous version of ancombc.

Thanks.
Jérémy

**Comment by FrederickHuangLin** [comment] 2022-10-18 17:25
Hi @jkcopela & @JeremyTournayre,

Thanks for your feedback!

I just located the issue of duplicate taxon names, it seems it was inherited from the `SummarizedExperiment` object. I am working on it now and will push a bug fix change by tomorrow.

I will keep you posted.

Thanks,
Huang

**Comment by FrederickHuangLin** [comment] 2022-10-20 03:08
Hi @jkcopela & @JeremyTournayre,

I have updated the package accordingly to resolve the bug. You can try it by downloading the devel version of `ANCOMBC` from GitHub.

Please note that the Bioconductor branch RELEASE_3_15 is now frozen, so there will be no update of `ANCOMBC` there. New features of `ANCOMBC` will be available on the Bioconductor branch RELEASE_3_16 (in early November).

Thanks for your support to `ANCOMBC`!

Best,
Huang

**Comment by jkcopela** [comment] 2022-10-24 18:01
Hi Huang,

Thank you for the update! However I am still getting the same error. I've downloaded ANCOMBC from github as you suggested, but the error remains.

I am not sure if this is my error with downloading the development version, or something that is still inherently different about my data. 

@JeremyTournayre is this problem resolved for you?

Julia

Edit: I followed this advice and just renamed all of the uncultured taxa with the name of the higher level taxa, which has worked! https://github.com/joey711/phyloseq/issues/850  

I see that the problem was the ANCOMBC2 was not pulling the full taxa name string, just the current level, leaving multiple results from different taxonomic lineages  with the same "uncultured" assignment. However, this does not work if there are multiple levels (Genus and Family, etc) with "uncultured", as we run in to the same problem as before.

**Comment by JeremyTournayre** [comment] 2022-11-08 14:40
Hello, thanks for the answers!

I just tested the latest version today (ANCOMBC_2.0.1.tar.gz).

None of the solutions worked: updating ANCOM BC and renaming all of the uncultured taxa with the name of the higher level taxa.

I think my problem come from my data because they comes from QIIME 2 and I have multiple features (=sequences) which got the same taxonomic affiliation, not only the "uncultured" ones. 
Strangely, when I go back to the version 1.6.2 (R-4.2.1 CMD INSTALL ANCOMBC_1.6.2.tar.gz), I don't have any problem.

My motivation to update ANCOM BC is to have the pairwise option because at this moment I'm doing the pairwise manually by changing the reference group, with this method I think the pvalues are not corrected correctly.

If you want my data to help you to find and solve the bug you can ask me.

Best, Jérémy Tournayre

**Comment by FrederickHuangLin** [comment] 2022-11-08 15:37
Hi @jkcopela & @JeremyTournayre,

Thanks for your feedback! My apologies for the issues you are experiencing. 

The `ANCOMBC` package before version 1.6.2 uses `phyloseq` format for the input data structure, while since version 2.0.0, it has been transferred to `tse` format. I think the issue is probably due to the difference in the ways that these two formats handle the input data.

@JeremyTournayre it would be super helpful if you are willing to share with me your data! Please be sure that the data are de-identified and contain no patient information. If you don't mind, could you please send the data to my email at huanglinfrederick@gmail.com? Thanks in advance!

I will keep you guys updated once I figured out the issue.

Best,
Huang

**Comment by Palliko** [comment] 2022-11-16 16:36
Hello,

I am trying to work with Family levels with ANACOM it worked but when I am trying to do that at the genus level it shows
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘Genus: Clostridium’ 

I am using the phyloseq object format
Is there any problem with my data frame or phyloseq format?

**Comment by JeremyTournayre** [comment] 2022-11-17 08:09
Hello,

I have done a new installation of ANCOM on another computer and there is no problem anymore O.O.  It works with R-4.2.1 CMD INSTALL ANCOMBC_2.0.1.tar.gz ! 

Meanwhile the initial computer (it's a server) which I had a problem was unavailable was restarted and the error don't show up after I had reinstalled the latest version of ANCOM (2.0.1). I think I may had installed the new version of ANCOM incorrectly.

Sorry to have disturbed you.

Have a good day, Jérémy Tournayre

**Comment by FrederickHuangLin** [comment] 2022-11-17 14:51
Thanks for your feedback, @JeremyTournayre! I am glad the problem was solved!

Hi @Palliko ! It seems the problem is probably the `ANCOMBC` version issue. Could you try to update it to version 2.0.1 or reinstall it if it has been installed before?

Best,
Huang

**Closed as completed by FrederickHuangLin** 2022-11-17 14:51 UTC
Labels: bug

**Comment by Palliko** [comment] 2022-11-22 22:48
Hello,

I am totally new to this area of analysis.
I am having a problem with the script for my analysis using ancom.
My study approach is 2 x 2 factorial design i.e 2 genetic lines and 2 efficiencies ( for example, E line high and low, Z line high and low efficiency). I want to see the interaction of 2 genetic lines with the month as a random effect

It shows an error while using the below script

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘NSBS’ for signature ‘"formula" 

out = ancom(data = NULL, assay_name = NULL,
+             tax_level = "Genus", phyloseq = Digestibilitya,
+             p_adj_method = "holm", prv_cut = 0.10, lib_cut = 20000,
+             main_var = "Genotype + Efficiency + Genotype:Efficiency", adj_formula = NULL,
+             rand_formula = "MONTH", lme_control = NULL,
+             struc_zero = TRUE, neg_lb = TRUE, alpha = 0.05, n_cl = 1)

Can anyone give me a suggestion on my approach? Can we able to do the interaction approach using ancom?
It would be highly appreciated if you provide me right direction on my approach. 

Thanks
